//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remnant.DataGateway.Sdk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remnant.DataGateway.Sdk.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find definition of bind parameter &apos;{0}&apos;, define bind parameters on ISql interface..
        /// </summary>
        public static string BindParameterNotDefined {
            get {
                return ResourceManager.GetString("BindParameterNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column &apos;{0}&apos; is already added for the &apos;{1}&apos; operation. Duplicates are not allowed..
        /// </summary>
        public static string ColumnAlreadyAdded {
            get {
                return ResourceManager.GetString("ColumnAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection type and connection string is already registered under the name &apos;{0}&apos;..
        /// </summary>
        public static string DbAlreadyRegistered {
            get {
                return ResourceManager.GetString("DbAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database context is already instantiated for the current thread and cannot be overriden..
        /// </summary>
        public static string DbContextExists {
            get {
                return ResourceManager.GetString("DbContextExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; specified as the database key cannot be null..
        /// </summary>
        public static string DbKeyNull {
            get {
                return ResourceManager.GetString("DbKeyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database name &apos;{0}&apos; has already been registered with the DbManager..
        /// </summary>
        public static string DbNameAlreadyRegistered {
            get {
                return ResourceManager.GetString("DbNameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database name &apos;{0}&apos; is not registered with the DbManager..
        /// </summary>
        public static string DbNameNotRegistered {
            get {
                return ResourceManager.GetString("DbNameNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bind parameter &apos;{0}&apos; is already defined..
        /// </summary>
        public static string DuplicateBindParameter {
            get {
                return ResourceManager.GetString("DuplicateBindParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column &apos;{0}&apos; is already defined..
        /// </summary>
        public static string DuplicateColumn {
            get {
                return ResourceManager.GetString("DuplicateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table/alias &apos;{0}&apos; already specified. Ensure aliases are specified correctly..
        /// </summary>
        public static string DuplicateFromEntity {
            get {
                return ResourceManager.GetString("DuplicateFromEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection type &apos;{0}&apos; cannot be found. Unable to connect to the database &apos;{1}&apos;..
        /// </summary>
        public static string InvalidConnectionType {
            get {
                return ResourceManager.GetString("InvalidConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statement is not containing a CTE statement..
        /// </summary>
        public static string InvalidCteStatement {
            get {
                return ResourceManager.GetString("InvalidCteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;From&apos; statement is invalid, expecting only selection of 1 table..
        /// </summary>
        public static string InvalidFrom {
            get {
                return ResourceManager.GetString("InvalidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insert return key statement requires 1 placeholder which is not the case. Check the specific DbConfiguration implementation for database type &apos;{0}&apos;..
        /// </summary>
        public static string InvalidInsertReturnKeyStatement {
            get {
                return ResourceManager.GetString("InvalidInsertReturnKeyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DbManager is alreay set to enbale logging.
        /// </summary>
        public static string LoggingAlreadyEnabled {
            get {
                return ResourceManager.GetString("LoggingAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection string is not specified. You must call &apos;DbMananger.ConnectionString&apos; to set your connection string..
        /// </summary>
        public static string NoConnectionString {
            get {
                return ResourceManager.GetString("NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current join definition to perform a &apos;join on&apos; criteria..
        /// </summary>
        public static string NoCurrentJoinDefinition {
            get {
                return ResourceManager.GetString("NoCurrentJoinDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here are no data type mappings defined for schema &apos;{0}&apos;..
        /// </summary>
        public static string NoDataTypesMapped {
            get {
                return ResourceManager.GetString("NoDataTypesMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database context cannot be resolved for the current &apos;dbName&apos;, Please ensure you have registered your database..
        /// </summary>
        public static string NoDbContext {
            get {
                return ResourceManager.GetString("NoDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database type is not specified. You must call &apos;DbMananger.DatabaseType&apos; and set the type..
        /// </summary>
        public static string NoDbType {
            get {
                return ResourceManager.GetString("NoDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data type mapping found between .Net and database schema &apos;{0}&apos; for data type of &apos;{1}&apos;..
        /// </summary>
        public static string NoMappingForDataType {
            get {
                return ResourceManager.GetString("NoMappingForDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the stored procedure is not specified.
        /// </summary>
        public static string StoredProcNameNull {
            get {
                return ResourceManager.GetString("StoredProcNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start transaction for it has already been started..
        /// </summary>
        public static string TransactionAlreadyStarted {
            get {
                return ResourceManager.GetString("TransactionAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction is already committed and {0} cannot be performed..
        /// </summary>
        public static string TransactionCommitted {
            get {
                return ResourceManager.GetString("TransactionCommitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to {0} because the transaction has not been created..
        /// </summary>
        public static string TransactionNotStarted {
            get {
                return ResourceManager.GetString("TransactionNotStarted", resourceCulture);
            }
        }
    }
}
